# Shopify App configuration
# Fill in your own values before submitting to the App Store

name = "JENNi Same‑Day Delivery"
client_id = "${SHOPIFY_API_KEY}"
application_url = "${SHOPIFY_APP_URL}"
embedded = true

[access_scopes]
scopes = "read_products,write_products,read_themes,read_script_tags"

[auth]
redirect_urls = [
  "${SHOPIFY_APP_URL}/auth/callback"
]

[app_proxy]
# Partner Dashboard → App setup → App proxy must match these
url = "${SHOPIFY_APP_URL}"
subpath = "v1"
prefix = "apps/jenni"

[webhooks]
api_version = "2024-07"

# Core webhooks for public apps
[[webhooks.subscriptions]]
topics = [
  "customers/data_request",
  "customers/redact",
  "shop/redact"
]
uri = "${SHOPIFY_APP_URL}/webhooks/gdpr"

# Optional: product sync
[[webhooks.subscriptions]]
topics = ["products/create", "products/update"]
uri = "${SHOPIFY_APP_URL}/webhooks/shopify/products"

# App uninstall cleanup
[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "${SHOPIFY_APP_URL}/webhooks/shopify/app-uninstalled"
